name: Deploy Hugo Blog

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -ex
            cd ~/preppstacxblog
            git pull origin master
            git submodule update --init --recursive
            hugo
            echo "Hugo build fertig"
            sudo rm -rf /var/www/preppstablog/*
            echo "Altes Verzeichnis gelöscht"
            sudo cp -r public/* /var/www/preppstablog/
            echo "Neue Dateien kopiert"
            sudo systemctl reload nginx
            echo "Nginx neu geladen"
